# roll_probability.py 코드 리뷰 (숫자 직접 검증)

- **작성일**: 2026-08-24
- **대상**: `/output/economy/roll_probability.py` (226줄)
- **방법**: 코드 정독 + **직접 호출로 수치 검증**. "테스트 통과" 기록은 무시.
- **정책**: 수정 금지(검토만). 발견 사항은 라인 + 수정 방향만 제시.

---

## [1] 실제 시그니처 / 반환 구조 (그대로 보고)

```python
def unit_hit_probability(
    target_champion: str,      # Set 17 챔피언 이름 (07_roster.json ko_KR 이름)
    target_cost: int,          # 1~5
    level: int,                # 1~10
    target_copies_taken: int,      # target 챔피언이 이미 나간 장수
    cost_tier_copies_taken: int,   # 같은 코스트 티어 전체에서 소모된 장수 합
    num_rolls: int             # 리롤 횟수 (1 이상)
) -> dict
```

반환 dict (실측, `("진", 5, 9, 0, 0, 1)` 호출 기준):

| 키 | 타입 | 실측값 |
|---|---|---|
| `prob_per_slot` | float | 0.016667 |
| `prob_at_least_one_per_roll` | float | 0.080601 |
| `expected_count_over_rolls` | float | 0.083333 |
| `gold_per_expected_unit` | float | 24.0 |

내부 계산: `p_slot = dropRate[L][c] × (K_c − taken_target)/(K_c·N_c − taken_tier)` (L206-213),
`at_least_one = 1 − (1−p_slot)⁵` (L215), `expected = num_rolls·5·p_slot` (L216),
`gold_per_unit = num_rolls·2 / expected` (L217-218, expected=0이면 `inf`).

---

## [2] 시나리오 직접 호출 결과

공통 입력: `K = {1:29, 2:22, 3:18, 4:10, 5:9}`, `N = {1:14, 2:13, 3:13, 4:14, 5:9}`,
드랍률 L9 5cost=15%, L5 1cost=45% (03_drop_rates.json 실측, L5 합계=100% 확인).

### (a) L9 / 5코스트 / taken=0 → **FAIL (티켓 기대 범위와 불일치)**

```
p_slot = 0.15 × 9/81 = 1.6667%
prob_at_least_one = 1 − (1−0.016667)⁵ = 8.0601%
```

- 티켓 기대: **1~3%**. 실측: **8.06%** → 범위 밖.
- 단, 계산 자체는 데이터와 정확히 일치함: `0.15 × 9/81`은 드랍률(15%)과 풀 구성(9장/81장)에서
  기계적으로 도출된 값. 즉 **모델/코드의 오류가 아니라 티켓의 기대 범위(1~3%)가 데이터와
  맞지 않는다**. 1~3%가 어디에서 나온 추정인지 출처 확인 필요. (→ F-R3)

### (b) L5 / 1코스트 / taken=0 (대상: 나서스) → **FAIL (티켓 기대 범위와 불일치)**

```
p_slot = 0.45 × 29/406 = 3.2143%
prob_at_least_one = 1 − (1−0.032143)⁵ = 15.0709%
```

- 티켓 기대: **20~40%**. 실측: **15.07%** → 범위 밖.
- (a)와 같은 성질: 계산은 데이터와 정합하고, 티켓 기대치가 과대. L5 1코스트 드랍률 45%에
  풀 406장(29×14) 중 대상 29장이면 슬롯당 3.21%, 5슬롯 최소 1개 15.07%가 정확함. (→ F-R3)

### (c) L9 / 5코스트 / "티어 전체 절반 소모" → **FAIL (티켓 서술과 반대 방향)**

티켓 서술: "티어 전체 장수의 절반이 이미 소모 → (a) 대비 확률이 대략 절반 근처로 **떨어지는지**".

실측 (티어 풀 = 9×9 = 81장, 절반 = 40장 소모):

**해석 A — 대상(진) 자체는 소모 안 됐고, 나머지 티어만 40장 소모 (`taken_target=0, taken_tier=40`)**

```
p_slot = 0.15 × 9/41 = 3.2927%   (a)의 1.97배
at_least_one = 15.4144%          (a)의 1.91배
```

**확률이 2배로 오른다.** 반대로 떨어지지 않는다.

**해석 B — 대상(진) 자체 장수가 절반(4~5장) 소모, 티어는 대상만큼만 (`taken_target=4~5, taken_tier=동일`)**

```
taken=4: p_slot = 0.15 × 5/81 = 0.926%  → (a)의 55.5%
taken=5: p_slot = 0.15 × 4/81 = 0.741%  → (a)의 44.4%
```

**이 해석에서만 "절반 소모 → 확률 절반" 성립.**

**판정**:
- 구현은 **무복위(without replacement) 모델** — 티어가 줄어드면 남은 풀에서 대상의 상대 비중이
  올라가므로 해석 A의 "상승"이 수학적으로 올바른 행동이다. 티켓의 "떨어진다"는 기대는
  "소모 = 대상 포함 균등 소모"나 "드랍률이 고정된 독립 슬롯"이라는 다른 가정 기반.
- **선형성 자체는 성립**: 분모 고정 시 `p_slot ∝ (K_c − taken_target)` 정확 선형
  (해석 B에서 taken 0→9에 대해 p_slot이 3.29% → 0.00% 정확 비례, 실측 확인).
- 티켓 서술대로 "(a) 대비 절반 근처로 떨어진다"는 기대는 **해석 A로는 실패**(1.91배로 상승),
  **해석 B로만 통과**. 서술의 "티어 전체 장수 절반"이 "대상의 장수 절반"을 의미했는지
  사용자 확인 필요. 코드 수정은 이 확인 전까지 불필요.

---

## [3] load_roster() 데이터 출처 + DDragon 직접 대조 → **PASS**

- `load_roster()` (L97-132)는 런타임에 DDragon을 읽지 않는다.
  **`/output/tft_guide/07_roster.json`** (스냅샷)을 로드.
- 스냅샷 출처(파일 내 `source`/`source_note`): DDragon v16.16.1
  `TFT_DDragon/data/ko_KR/champion.json`에서 **`TFT17_` prefix 필터 + `_TraitClone` 제외
  + cost 0 가짜 유닛(`TFT17_DarkStar_FakeUnit`, `TFT17_Enemy_Aatrox`) 제외**로 추출.

**직접 대조** — champion.json에서 `TFT17_` prefix만 필터링(총 66개) 후 클론 1개 제외 = 65개,
cost 0 2개 제외 = **63개**:

| 코스트 | DDragon 직접 세기 | 07_roster.json `counts` | `names` 길이 | 판정 |
|---|---|---|---|---|
| 1 | 14 | 14 | 14 | 완전 일치 ✓ |
| 2 | 13 | 13 | 13 | 완전 일치 ✓ |
| 3 | 13 | 13 | 13 | 완전 일치 ✓ |
| 4 | 14 | 14 | 14 | 완전 일치 ✓ |
| 5 | 9 | 9 | 9 | 완전 일치 ✓ |
| 합계 | 63 | 63 | 63 | ✓ |

- **이름 단위 대조도 cost별 0차이**(extra/missing 모두 공집합). 미스 포츈 클론
  (`TFT17_MissFortune_TraitClone`, cost 3) 제외로 cost 3이 14→13이 되는 것이 정확함.
- ⚠️ 참고: champion.json은 **모든 세트 합산 270개 엔트리**를 담고 있음(전체 cost 분포
  {0:39, 1:42, 2:45, 3:48, 4:52, 5:38, 7:6}). prefix 없이 그냥 세으면 숫자가 완전히 틀리므로,
  로스터의 `TFT17_` 필터링은 필수였고 실제로 그렇게 추출됨.
- `load_roster()`는 `counts` 필드와 `names` 길이 불일치 시 ValueError(L122-125) — 자체 무결성 검증 존재.

---

## [4] 레벨 11 차단 → **PASS**

```python
>>> unit_hit_probability("진", 5, 11, 0, 0, 1)
ValueError: 레벨 11은/는 로드된 드랍률 테이블에 없습니다. exists_in_game=false 레벨(예: 11)은
게임에 존재하지 않아 로드 시 제외됩니다. 사용 가능한 레벨: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
```

- 로드된 레벨 = `[1..10]` (L84-85에서 `exists_in_game: false` 행 제외 로직 실측 확인).
- 03_drop_rates.json의 레벨 11 행(`exists_in_game: false`)이 실제로 로드에서 사라진 것 확인.
- 에러 메시지에 사용 가능 레벨 목록까지 포함되어 UX 양호.

---

## [5] "5슬롯 중 최소 1개" 공식 → **PASS (5×p 근사 미사용)**

- **L215**: `p_at_least_one = 1.0 - (1.0 - p_slot) ** SHOP_SLOTS` — **정확식 `1−(1−p)⁵` 사용**.
  5×p 근사식 사용 흔적 없음 (AST/grep으로 L215 외 다른 계산 경로 없음).
- 수치 검증 (b)의 p=0.032143에서):
  - 정확식: 15.0709% ← **코드 반환값과 1e-12 이내 일치**
  - 5×p 근사: 16.0714% (오차 1.00%p)
  - p가 클수록 벌어지는 오차가 실제로 존재함을 확인 → 근사식이었으면 문제였을 것. 정확식이라 무관.
- 기대 개수(L216)는 슬롯 독립 가정을 쓰되 "의존성이 있어도 성립(기댓값의 선형성)"이라
  docstring L29에 명시 — 정당.

---

## 발견 항목 (수정 안 함 — 방향만)

| ID | 심각도 | 위치 | 내용 | 수정 방향 |
|---|---|---|---|---|
| **F-R1** | **높음** | L194-203 | **두 taken 파라미터의 교차 검증 부재** → 물리적으로 불가능한 상태를 받아들이고, **확률이 100%를 초과**한다. 실측: `unit_hit_probability("진", 5, 9, 0, 80, 1)` — `target_copies_taken=0, cost_tier_copies_taken=80`은 "5코스트 81장 중 80장이 소모됐는데 모두 진이 아님" 상태인데, 진 9장이 아직 풀에 있으면서 티어 잔여가 1장이므로 **불가능**. 함수는 이를 검증 없이 통과시켜 `p_slot = 0.15 × 9/1 = 135%`, `prob_at_least_one = 100.53%` (1−(−0.35)⁵), `expected = 6.75/롤` (물리 최대 5)을 반환. | L199-203에 교차 검증 추가: `if cost_tier_copies_taken - target_copies_taken > k_copies * (n_varieties - 1): raise ValueError(...)` (대상 외 소모량은 대상 외 전체 장수 K·(N−1)를 초과 불가). 방어적으로 L213에 `p_slot = min(p_slot, 1.0)` 클램프도 함께. |
| **F-R2** | 낮음 | L179, L136 | `isinstance(x, int)` 검증이 **`bool`을 허용** — `num_rolls=True`는 1로, `target_copies_taken=False`는 0으로 묵인됨. | `isinstance(value, int) and not isinstance(value, bool)` 또는 `type(value) is int`. |
| **F-R3** | 정보 | — | 티켓의 (a) 1~3%, (b) 20~40% 기대 범위가 데이터 기반 실측(8.06%, 15.07%)과 불일치. 코드/데이터는 내부 정합(드랍률 L5 합 100%, 로스터 DDragon 일치)이므로 **기대 범위 쪽이 잘못되었을 가능성 높음**. | 1~3% / 20~40%의 출처(어떤 가이드/가정)를 확인. 출처가 없으면 이 티켓의 기대 범위를 실측 기준으로 갱신. |

---

## 종합 판정

| 항목 | 판정 |
|---|---|
| [1] 시그니처/반환 구조 | 보고 완료 (위) |
| [2a] L9 5cost taken=0, 1~3% 기대 | **FAIL** — 실측 8.06% (계산은 정합, 기대치가 잘못) |
| [2b] L5 1cost taken=0, 20~40% 기대 | **FAIL** — 실측 15.07% (상동) |
| [2c] 티어 절반 소모 → 절반으로 하락 | **FAIL (서술 기준)** — 해석 A(대상 미소모)면 1.91배로 **상승**(무복위 모델의 올바른 행동), 해석 B(대상 자체 절반)에서만 44~56%로 하락. 선형성은 대상 소모량에 대해 정확히 성립 |
| [3] load_roster ↔ DDragon 대조 | **PASS** — 14/13/13/14/9 = 63, 이름 단위 완전 일치 |
| [4] 레벨 11 차단 | **PASS** — ValueError + 사용 가능 레벨 안내 |
| [5] 최소 1개 공식 | **PASS** — 정확식 1−(1−p)⁵ (L215), 5×p 근사 미사용, 수치 확인 |

**결론**: 핵심 계산(드랍률×풀비중, 정확식 5슬롯 집계, 레벨 11 차단, 로스터 무결성)은
숫자로 검증되어 **올바르다**. 그러나 **F-R1(교차 검증 부재 → p>1 반환)은 실제 버그**이며
다음 티켓에서 수정 권장. [2]의 범위/방향 불일치 3건은 코드 오류가 아니라 **티켓 기대치가
모델과 데이터에 맞지 않는 것**이므로, F-R3 확인과 함께 기대 기준을 재조정할 것.
